#!/usr/bin/env bash

echo "¡Bien hecho por seguir practicando en GitHub!"
echo "El aprendizaje nunca se detiene, y cada vez que practicas, te vuelves más habilidoso."
echo "Sigue adelante y no te detengas ahora."
echo "Recuerda que la práctica hace al maestro."
